---
# common parameters
n_cores: &cores 3

# This is an ordered dict that contains the order in which the steps are run.
run_sequence: !!omap
  - 1: 'basic_check'
  - 2: 'fill_data'
  - 3: 'infer_build'
  - 4: 'write_csv'

steps:
  basic_check: # see https://cloufield.github.io/gwaslab/Standardization/
    run: True
    n_cores: *cores
  infer_build: # see https://cloufield.github.io/gwaslab/InferBuild/
    run: False
  fill_data: # see https://cloufield.github.io/gwaslab/Conversion/#fill_data
    run: True
    to_fill: ['MLOG10P', 'Z']
    overwrite: False
    extreme: False
  harmonize: # see https://cloufield.github.io/gwaslab/Harmonization/
    run: True
    basic_check: False
    n_cores: *cores
    ref_seq: "data/GCA_000001405.14_GRCh37.p13_full_analysis_set.fna"
    ref_infer: "data/EUR.ALL.split_norm_af.1kgp3v5.hg19.vcf.gz"
    ref_alt_freq: "AF"
    remove: "True"
    removedup_args: {'mode': "md",'keep': 'first','keep_col': "MLOG10P" }
  liftover: # see https://cloufield.github.io/gwaslab/LiftOver/
    run: False
    n_cores: *cores
    from_build: "19"
    to_build: "38"
    remove: True
  report_summary:
    run: True
  report_inflation_factors:
    run: True
    workspace: "if"
  qq_manhattan_plots:
    run: True
    stratified : True
    maf_bins:  [(0, 0.01), (0.01, 0.05), (0.05, 1)]
    scaled: True
    build: "19"
    skip: 1
    dist: 2
    sig_level: 5e-8
    workspace: "plots"
  write_same_input_format:
    run: False
    workspace: "outputs"
  # see https://cloufield.github.io/gwaslab/Format/ for more details on writing options
  write_ldsc:
    run: False
    workspace: "ldsc"
    fmt: "ldsc"
  write_metal:
    run: False
    workspace: "metal"
    fmt: "metal"
  write_regenie:
    run: False
    workspace: "regenie"
    fmt: "regenie"
  write_vcf:
    run: False
    workspace: "vcf"
    fmt: "vcf"

# IO
root_path: "results"
log_filename: "gwaspipe.log"
report_if_filename: "report_if_placeholder.txt"
